#Quarkus port
quarkus.http.port=8090
#
javax.faces.PROJECT_STAGE=Production
#
quarkus.live-reload.watched-resources=META-INF/resources/

#
# datasource configuration
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = admps
quarkus.datasource.password = admpwd
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5433/app

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.database.generation=update